
x-superset-image: &superset-image artv3:latest

x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - superset_home:/app/superset_home
  - ./DGUM_Cetificates:/app/superset/security/certs

x-superset-extra-hosts: &superset-extra-hosts
  - "art-di-srv.datagearbi.dom:192.168.3.35"

services:
  redis:
    image: redis:7
    container_name: ARTV3_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      ARTV3_network:
        ipv4_address: 10.150.7.2

  # db:
  #   image: postgres:15
  #   container_name: ARTV3_db
  #   restart: unless-stopped
  #   env_file:
  #     - path: docker/.env
  #       required: true
  #     - path: docker/.env-local
  #       required: false
  #   volumes:
  #     - db_home:/var/lib/postgresql/data
  #     - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   networks:
  #     ARTV3_network:
  #       ipv4_address: 10.150.7.3

  ARTV3_app:
    image: *superset-image
    container_name: ARTV3_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    ports:
      - "9065:8088"
    depends_on:
      ARTV3_init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    extra_hosts: *superset-extra-hosts
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
    networks:
      ARTV3_network:
        ipv4_address: 10.150.7.4

  ARTV3_init:
    image: *superset-image
    container_name: ARTV3_init
    command: ["/app/docker/docker-init.sh"]
    user: "root"
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    depends_on:
      redis:
        condition: service_started
    volumes: *superset-volumes
    extra_hosts: *superset-extra-hosts
    healthcheck:
      disable: true
    environment:
      SUPERSET_LOAD_EXAMPLES: "${SUPERSET_LOAD_EXAMPLES:-no}"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
    networks:
      ARTV3_network:
        ipv4_address: 10.150.7.5

  ARTV3_worker:
    image: *superset-image
    container_name: ARTV3_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    user: "root"
    restart: unless-stopped
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    depends_on:
      ARTV3_init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    extra_hosts: *superset-extra-hosts
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"
        ]
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
    networks:
      ARTV3_network:
        ipv4_address: 10.150.7.6

  ARTV3_worker_beat:
    image: *superset-image
    container_name: ARTV3_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    user: "root"
    restart: unless-stopped
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    depends_on:
      ARTV3_init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    extra_hosts: *superset-extra-hosts
    healthcheck:
      disable: true
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
    networks:
      ARTV3_network:
        ipv4_address: 10.150.7.7

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false

networks:
  ARTV3_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.150.7.0/24
          gateway: 10.150.7.1